package dev.simplemachine.opengl.glenum;

import org.lwjgl.opengl.GL45;

public enum QueryType {
    SAMPLES_PASSED(GL45.GL_SAMPLES_PASSED),
    ANY_SAMPLES_PASSED(GL45.GL_ANY_SAMPLES_PASSED),
    ANY_SAMPLES_PASSED_CONSERVATIVE(GL45.GL_ANY_SAMPLES_PASSED_CONSERVATIVE),
    TIME_ELAPSED(GL45.GL_TIME_ELAPSED),
    TIMESTAMP(GL45.GL_TIMESTAMP),
    PRIMITIVES_GENERATED(GL45.GL_PRIMITIVES_GENERATED),
    TRANSFORM_FEEDBACK(GL45.GL_TRANSFORM_FEEDBACK),
    TRANSFORM_FEEDBACK_PRIMITIVES_WRITTE(GL45.GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN);


    public int constant;

    QueryType(int constant) {
        this.constant = constant;
    }

}
